# Generated by Django 6.0.5 on 2026-05-14 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Game Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Game Description')),
                ('developer', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('age_rating', models.CharField(blank=True, max_length=10, verbose_name='Age Rating')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Supported Languages')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, verbose_name='Cover Image URL')),
                ('metacritic_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Metacritic Score')),
                ('steam_app_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Steam App ID')),
                ('igdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='IGDB ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
    ]
